config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events, only: [:destroy, :show, :index, :new, :create] do
    resources :participations, only: [:create]
    member do
      put 'like', to: 'events#like'
      put 'unlike', to: 'events#unlike'
      put 'like_home', to: 'events#like_home'
      put 'unlike_home', to: 'events#unlike_home'
      put 'like_dashboard', to: 'events#like_dashboard'
      put 'unlike_dashboard', to: 'events#unlike_dashboard'
    end
  end

  get 'dashboard', to: 'pages#dashboard'
  resources :ngos, only: [:show, :new, :create] do
    member do
      put 'follow', to: 'ngos#follow'
      put 'unfollow', to: 'ngos#unfollow'
    end
  end
end

app/views/shared/_event_buttons.html.erb
<div class="event-button">
  <% if event.end_date < DateTime.now %>
    <%= link_to event_path(event) do %>
      <button class="btn btn-secondary">Terminé</button>
    <% end %>
  <% elsif user_signed_in? == false %>
    <%= link_to "Je participe", event_participations_path(event), method: :post, id: "register-link", class: "btn btn-success" %>
  <% elsif current_user.participations.find_by(event_id: event.id) %>
    <%= link_to event_path(event) do %>
      <button class="btn btn-warning">Déjà inscrit</button>
    <% end %>
  <% elsif event.seats_left.zero? %>
    <%= link_to event_path(event) do %>
      <button class="btn btn-danger my-2">Complet</button>
    <% end %>
  <% elsif current_user %>
    <%= link_to event_participations_path(event), method: :post, id: "register-link", remote: true, class: "hidden" do %>
      <button id="sweet-alert-register" class="btn btn-success">Je participe</button>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- yizhu: added footer -->
<div class="footer mt-5">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> En savoir plus sur nous
  </div>
</div>

app/views/shared/_navbar-home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" id="navbar-home">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Logo_CommitHood.png", id: "logo-navbar-all" %>
    <%= image_tag "Logo_CommitHood_white.png", id: "logo-home" %>

    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Tous les événements", events_path, class: "nav-link", id: "nav-link-home1" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Tableau de bord", dashboard_path, class: "nav-link", id: "nav-link-home2" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar user-photo", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 40, width: 40, crop: :fill %>
          <% else %>
            <%= image_tag "https://oozou.com/assets/placeholder-e61f8e40396b6f3d78281bfa3b2d5ca202616f0e3f9931d451a49d4c2ddfcfea.jpg", alt: "empty-avatar", class: "avatar-bordered user-photo", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Tableau de bord", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Mettre à jour vos informations", "#", class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Tous les événements", events_path, class: "nav-link", id: "nav-link-home1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link", id: "nav-link-home2" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Logo_CommitHood.png" %>

    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Tous les événements", events_path, class: "nav-link", id: "navbar-link-all"%>
        </li>
        <li class="nav-item active">
          <%= link_to "Tableau de bord", dashboard_path, class: "nav-link", id: "navbar-link-all"%>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar user-photo", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 40, width: 40, crop: :fill %>
          <% else %>
            <%= image_tag "https://oozou.com/assets/placeholder-e61f8e40396b6f3d78281bfa3b2d5ca202616f0e3f9931d451a49d4c2ddfcfea.jpg", alt: "empty-avatar", class: "avatar-bordered user-photo", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Tableau de bord", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Mettre à jour vos informations", "#", class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Tous les événements", events_path, class: "nav-link", id: "navbar-link-all" %>
        </li>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link", id: "navbar-link-all" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_tag_icons.html.erb
<% event.tag_list.map do |tag| %>
  <%= image_tag "#{tag.parameterize}.png", class:"event-tag" %>
<% end %>