config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events, only: [:destroy, :show, :index, :new, :create] do
    resources :participations, only: [:create]
    member do
      put 'like', to: 'events#like'
      put 'unlike', to: 'events#unlike'
      put 'like_home', to: 'events#like_home'
      put 'unlike_home', to: 'events#unlike_home'
      put 'like_dashboard', to: 'events#like_dashboard'
      put 'unlike_dashboard', to: 'events#unlike_dashboard'
    end
  end

  get 'dashboard', to: 'pages#dashboard'
  resources :ngos, only: [:show, :new, :create] do
    member do
      put 'follow', to: 'ngos#follow'
      put 'unfollow', to: 'ngos#unfollow'
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_votable cacheable_strategy: :update_columns

  belongs_to :ngo
  has_one_attached :photo
  has_many :participations
  has_many :users, through: :participations
  has_many :event_causes
  has_many :causes, through: :event_cause
  validates :name, :start_date, :end_date, :description, :seats, :address, presence: true
  # Kally : seats validation
  validates :seats, numericality: { greater_than: 0 }
  validates :seats_left, numericality: { greater_than_or_equal_to: 0 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  acts_as_taggable_on :tags
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_event, only: [:show, :destroy]

  # yizhu: add index controler to show all events
  def index

    @address = params[:address]
    @causes = params.select{|k,v| k.include?('user_cause')}.values

    if @causes.size > 0;
      @causes
    elsif params[:user_cause].present?
      @causes = params[:user_cause]
    else
      @causes = "Tous les thèmes"
    end

    # select_events = policy_scope(Event).geocoded.where(:start_date >= Time.now)

    if !@causes.nil? && (!@causes.include?("Tous les thèmes")) && (params[:address].present?)
      @events = policy_scope(Event).geocoded.near(@address, 8).tagged_with(@causes, any: true)

    elsif !@causes.nil? && (!@causes.include?("Tous les thèmes"))
      @events = policy_scope(Event).geocoded.tagged_with(@causes, any: true)

    elsif params[:address].present?
      @events = policy_scope(Event).geocoded.near(@address, 8)

    else
      @events = policy_scope(Event).geocoded.order(start_date: :desc)
    end

    # Kally
    @participations = Participation.all
    seats_left # private method below to count seats_left
    # fr_datetime

    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        title: event.tag_list,
        image_url: helpers.asset_url(
          case event.tag_list.first
          when "Environnement"
            "tag-environment.png"
          when "Bien-être animal"
            "tag-animal.png"
          when "Culture"
            "tag-culture.png"
          when "Formation"
            "tag-formation.png"
          when "Isolement"
            "tag-isolement.png"
          when "Jeunesse"
            "tag-jeunesse.png"
          when "Personnes âgées"
            "tag-personnes-agees.png"
          when "Précarité"
            "tag-precarite.png"
          when "Santé"
            "tag-sante.png"
          when "Sport"
            "tag-sport.png"
          else
            "logo.png"
          end
          ),
        data_event_id: event.id
        # infoWindow: render_to_string(partial: "info_window", locals: { event: event })
      }
    end

    respond_to do |format|
      format.html
      format.json { render json: { markers: @markers } }
    end

    unless params[:address].nil? || params[:address] == ''
      location = Geocoder.search(params[:address])
      @lat = location[0].latitude
      @lng = location[0].longitude
      @marker = {
        lat: @lat,
        lng: @lng,
        image_url: helpers.asset_url('marqueur-rond-bordure.png')
      }
      @markers << @marker
    end
  end

  # Ilana
  def show
    @participation = Participation.new
  end

  def like
    set_event
    @event.liked_by current_user
    redirect_to events_path(anchor: "#{@event.id}")
  end

  def unlike
    set_event
    @event.unliked_by current_user
    redirect_to events_path(anchor: "#{@event.id}")
  end

  def like_home
    set_event
    @event.liked_by current_user
    redirect_to root_path(anchor: "event-home-#{@event.id}")
  end

  def unlike_home
    set_event
    @event.unliked_by current_user
    redirect_to root_path(anchor: "event-home-#{@event.id}")
  end

  def like_dashboard
    set_event
    @event.liked_by current_user
    redirect_to dashboard_path(anchor: "event-#{@event.id}")
  end

  def unlike_dashboard
    set_event
    @event.unliked_by current_user
    redirect_to dashboard_path(anchor: "event-#{@event.id}")
  end

  private

  # ilana
  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  #Yizhu

  # def filter_events_cause(events, causes)
  #   filter_events = []
  #     causes.each do |cause|
  #       @events.where(causes: cause)
  #     end
  #   filtered_events
  # end

  # Kally
  def seats_left
    @events.each do |event|
      if Participation.where(event_id: event.id)
        event_participations = Participation.where(event_id: event.id)
        event.seats_left = event.seats - event_participations.size
      else
        event.seats_left = event.seats
      end
      event.save
    end
  end

end

app/views/events/_card_event.html.erb
<div class="d-flex flex-wrap">
  <% events.each do |event| %>
    <div class="card-event-dashboard">
      <div class="card-event-cover">
        <%= cl_image_tag event.photo.key, alt: "event photo", class:"card-event-img",crop: :fill %>
      </div>
      <div class="card-event-infos-dashboard">
        <div class="d-flex align-self-stretch">

          <!-- Date column -->
          <div class="card-event-date col-2 text-center">
            <% if event.ngo.photo.attached? %>
              <%= cl_image_tag event.ngo.photo.key, class: "avatar-event-card" %>
            <% end %>
            <p><%= I18n.l(event.start_date, locale: :fr, format: :day_week) %></p>
            <p id="event-day-highlight"><%= I18n.l(event.start_date, locale: :fr, format: :day) %></p>
            <p><%= I18n.l(event.start_date, locale: :fr, format: :month).upcase %></p>
            <p id="card-event-hour"><%= I18n.l(event.start_date, locale: :fr, format: :hours) %></p>
          </div>

          <!-- Infos column -->
          <div class="card-event-details col-sm-7">
            <%= link_to event.ngo.name, ngo_path(event.ngo), id: "card-event-ngo" %>
<!--             <p id="card-event-ngo"><%= event.ngo.name %></p> -->
            <h2><%= event.name %></h2>
            <p><i class="fas fa-map-marker-alt"></i> <%= event.address %></p>
            <p><i class="fas fa-user-circle"></i> <%= event.seats_left %> bénévoles souhaités</p>
            <!-- Day counter -->
            <% if event.start_date > DateTime.now %>
              <p><i class="far fa-calendar-alt"></i> commence dans <%= ((event.start_date - DateTime.now) / 1.day).to_i %></p>
              <% if (event.start_date - DateTime.now) / 1.day).to_i > 1 %>
                jours
              <% else %>
                jour
              <% end %>
            <% elsif event.end_date > DateTime.now %>
              <p><i class="far fa-calendar-alt"></i> termine dans <%= ((event.end_date - DateTime.now) / 1.day).to_i %> <%= (((event.start_date - DateTime.now) / 1.day).to_i) > 1) ? "jours" : "jour" %></p>
            <% else %>
              <br>
            <% end %>
          </div>

          <!-- Button -->

            <% if event.end_date < DateTime.now %>
              <%= link_to event_path(event) do %>
                <button class="btn btn-secondary card-btn-home">Terminé</button>
              <% end %>
            <% elsif user_signed_in? == false %>
              <%= link_to "Je participe", event_participations_path(event), method: :post, id: "register-link", class: "btn btn-success card-btn-home" %>
            <% elsif current_user.participations.find_by(event_id: event.id) %>
              <%= link_to event_path(event) do %>
                <button class="btn btn-warning card-btn-home">Déjà inscrit</button>
              <% end %>
            <% elsif event.seats_left.zero? %>
              <%= link_to event_path(event) do %>
                <button class="btn btn-danger my-2 card-btn-home">Complet</button>
              <% end %>
            <% elsif current_user %>
              <%= link_to event_participations_path(event), method: :post, id: "register-link", remote: true, class: "hidden" do %>
                <button id="sweet-alert-register" class="btn btn-success card-btn-home">Je participe</button>
              <% end %>
            <% end %>

          <!-- Bookmark -->
            <% if user_signed_in? %>
              <% if current_user.liked? event %>
                <%= link_to unlike_event_path(event), class:"unlike-event bookmark-like-red", method: :put, remote: true do %>
                  <i class="fas fa-bookmark" id="unlike"></i>
                <% end %>
              <% else %>
                <%= link_to like_event_path(event), class: "interested bookmark-like-red", method: :put, remote: true do %>
                  <i class="far fa-bookmark" id="like-event"></i>
                <% end %>
              <% end  %>
            <% end %>


        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<!-- yizhu: add a container to all elements, with a row to display two sections -->
<%= render 'shared/navbar' %>
<div class="justify-content-center">

  <!-- yizhu: map section with cards -->

  <div class="d-flex map-cards">

    <!-- add button to attach the search bar -->
    <div class="search-bar-with-button">
            <!-- hide searchbar button -->
      <div class="button-menu">
        <i class="fas fa-caret-square-left" style="font-size: 40px"></i>
      </div>
      <!-- end of searchbar button -->

      <!-- add result filter and text search function -->
      <div class="search-bar-index">
        <%= form_tag events_path, method: "get" do %>
          <%= text_field_tag :address, params[:address].present? ? params[:address] : '', required: false, id: "event-address", label: false, placeholder: "Votre adresse" %>
          <%= submit_tag "Rechercher", class: "btn btn-success text-white mt-2" %>
          <div class="search-select-index mt-3">
            <h5>Choisissez vos Thèmes </h5>
            <div class="cause-list">
              <ul>
                <% Cause::CAUSES.each do |cause| %>
                  <li>
                    <label class="cause-select <%= cause.parameterize.split('-').first %> <%= @causes.include?(cause) ? "active" : "" %>">
                      <%= check_box_tag "user_cause_#{cause.downcase}", "#{cause}", params["user_cause_#{cause.downcase}"] == cause, id: "user_cause", style:'visibility: hidden'%>
                      <%= image_tag "#{cause == "Tous les thèmes" ? "logo" : cause.parameterize}.png", size: "20x20", alt: "alttext" %>  <%= cause %> (<%= cause == "Tous les thèmes" ? Event.all.size : Event.tagged_with("#{cause}").count %>)
                    </label>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
      <!-- result filter end -->

    </div>
    <!-- end of button with menue bar -->


    <!-- section of map, 100% of the larger -->
    <div id="map" class=""
      data-lng="<%= @lng %>"
      data-lat="<%= @lat %>"
      style="width: 100%; height: 90vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

      <!-- yizhu: section of cards for events show, 50% of the larger -->

    <div class="p-0" id="card-info">
      <!-- yizhu: insert events cards here -->
      <% @events.each do |event| %>
        <div class="card-info-window" id="event-<%= event.id %>" >

            <!-- Bookmark on photo -->
          <div class="bookmark-like-red">
            <% if user_signed_in? %>
              <% if current_user.liked? event %>
                <%= link_to unlike_event_path(event), class: "unlike-event", remote: true, method: :put do %>
                  <i class="fas fa-bookmark" id="unlike"></i>
                <% end %>
              <% else %>
                <%= link_to like_event_path(event), class: "interested", remote: true, method: :put do %>
                  <i class="far fa-bookmark" id="like-event"></i>
                  <div class="infobulle" style="display: none;">
                    <div class="infobulle-texte" id="Intéressé" >
                      Intéressé(e)
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% else %>
                <%= link_to new_user_session_path, class: "interested" do %>
                  <i class="far fa-bookmark" id="like-event"></i>
                <% end %>
            <% end  %>
          </div>

          <%= cl_image_tag event.photo.key, crop: :fill, class: "event-photo" %>


          <div class="card-info-window-infos">
            <div class="d-flex justify-content-between mb-3">

              <div>
                <h2><%= event.name %></h2>
                <p>
                  <%= render "shared/tag_icons", event: event %>
                </p>

               <p class="event-address"><i class="fas fa-map-marker-alt"></i> <%= event.address %></p>
                <p><i class="fas fa-user-circle"></i> <%= event.seats_left %> bénévoles souhaités</p>

                <p><i class="far fa-calendar-alt"></i><% if event.start_date.to_date == event.end_date.to_date %>
                <%= I18n.l(event.start_date, locale: :fr) %> - <%= I18n.l event.end_date, locale: :fr, format: :hours %>
                <% else %>
                <%= I18n.l(event.start_date, locale: :fr) %> - <%= I18n.l(event.end_date, locale: :fr) %>
                <% end %>
                </p>
              </div>

              <div class="d-inline">
                <div class="card-event-date text-center">
                  <strong>
                    <p><%= I18n.l(event.start_date, locale: :fr, format: :day_week) %></p>
                    <p class="event-day-highlight"><%= I18n.l(event.start_date, locale: :fr, format: :day) %></p>
                    <p><%= I18n.l(event.start_date, locale: :fr, format: :month).upcase %></p>
                    <p id="card-event-hour"><%= I18n.l(event.start_date, locale: :fr, format: :hours) %></p>
                  </strong>
                </div>
                <div class="event-button">
                  <% if event.end_date < DateTime.now %>
                    <%= link_to event_path(event) do %>
                      <button class="btn btn-secondary">Terminé</button>
                    <% end %>
                  <% elsif user_signed_in? == false %>
                    <%= link_to "Je participe", event_participations_path(event), method: :post, id: "register-link", class: "btn btn-success" %>
                  <% elsif current_user.participations.find_by(event_id: event.id) %>
                    <%= link_to event_path(event) do %>
                      <button class="btn btn-warning" style="color: white; width: 110px">Déjà inscrit</button>
                    <% end %>
                  <% elsif event.seats_left.zero? %>
                    <%= link_to event_path(event) do %>
                      <button class="btn btn-danger my-2">Complet</button>
                    <% end %>
                  <% elsif current_user %>
                    <%= link_to event_participations_path(event), method: :post, id: "register-link", remote: true, class: "hidden" do %>
                      <button id="sweet-alert-register" class="btn btn-success">Je participe</button>
                    <% end %>
                  <% end %>
                </div>

              </div>
            </div>
              <p class="mb-3"><%= event.description %></p>
              <div class="dropdown-divider my-4"></div>
              <div class="card-window-ngo">
                <div class="d-flex align-items-center">
                  <% if event.ngo.photo.attached? %>
                    <%= cl_image_tag event.ngo.photo.key, class: "avatar-event" %>
                  <% end %>
                  <div class="ml-3">
                    <h3><%= event.ngo.name %></h3>
                    <div class="follow-me">
                      <% if user_signed_in?  %>
                        <% if current_user.liked? event.ngo %>
                          <%= link_to unfollow_ngo_path(event.ngo.id), class: "unfollow-ngo", remote: :true, method: :put do %>
                            <i class="fas fa-heart" id="unlike-ngo"></i>
                          <% end %>
                        <% else %>
                          <%= link_to follow_ngo_path(event.ngo.id), class: "follow-ngo", remote: :true, method: :put do %>
                            <i class="far fa-heart" id="like-ngo"></i>
                          <% end %>
                        <% end  %>
                      <% else %>
                          <%= link_to new_user_session_path, class: "follow-ngo" do %>
                            <i class="far fa-heart" id="like-ngo"></i>
                          <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div>
                  <p class="my-2"><%= event.ngo.description %></p>
                  <%= link_to "Voir les événéments", ngo_path(event.ngo)  %>
                </div>
              </div>

          </div>
        </div>
      <% end %>
      <!-- yizhu: end of insert cards -->
    </div>
      <!-- end of cards section -->

  </div>
</div>

app/views/events/show.html.erb
<%= render 'shared/navbar'%>
<div class="container-event">
  <div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path @event.photo.key, crop: :fill %>')">
    <%= cl_image_tag @event.ngo.photo.key, alt: "event photo", crop: :fill, id: "avatar-ngo" %>
  </div>
  <div class="d-flex" id="events-details">
    <div class="col-8 ">
      <h1 class="bold"><%= @event.name %></h1>
      <p> <%= @event.description %></p>
    </div>
    <div class="card-event col-4">
      <p >Organisé par </p><h4><%= @event.ngo.name %></h4>
      <!-- <button class="btn">Suivre</button> -->
      <h3 class="mt-2"></h3>
          <div class="event-button my-3">
            <% if @event.end_date < DateTime.now %>
              <%= link_to event_path(@event) do %>
                <button class="btn btn-secondary">Terminé</button>
              <% end %>
            <% elsif user_signed_in? == false %>
              <%= link_to "Je participe", event_participations_path(@event), method: :post, id: "register-link", class: "btn btn-success" %>
            <% elsif current_user.participations.find_by(event_id: @event.id) %>
              <%= link_to event_path(@event) do %>
                <button class="btn btn-warning">Déjà inscrit</button>
              <% end %>
            <% elsif event.seats_left.zero? %>
              <%= link_to event_path(@event) do %>
                <button class="btn btn-danger my-2">Complet</button>
              <% end %>
            <% elsif current_user %>
              <%= link_to event_participations_path(@event), method: :post, id: "register-link", remote: true, class: "hidden" do %>
                <button id="sweet-alert-register" class="btn btn-success">Je participe</button>
              <% end %>
            <% end %>
          </div>
        <ol style="list-style-type:none;" id="ol-details">
          <li><i class="fas fa-map-marker-alt"></i> <%= @event.address%></li>
          <li><i class="fas fa-user-circle"></i><%= @event.seats_left %> bénévoles souhaités</li>
          <li><i class="far fa-calendar-alt"></i>
          <% if @event.start_date.to_date == @event.end_date.to_date %>
          <%= I18n.l(@event.start_date, locale: :fr) %> - <%= I18n.l @event.end_date, locale: :fr, format: :hours %>
          <% else %>
          <%= I18n.l(@event.start_date, locale: :fr) %> - <%= I18n.l(@event.end_date, locale: :fr) %>
          <% end %>
          </li>
        </ol>
    </div>
  </div>
</div>