config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events, only: [:destroy, :show, :index, :new, :create] do
    resources :participations, only: [:create]
    member do
      put 'like', to: 'events#like'
      put 'unlike', to: 'events#unlike'
      put 'like_home', to: 'events#like_home'
      put 'unlike_home', to: 'events#unlike_home'
      put 'like_dashboard', to: 'events#like_dashboard'
      put 'unlike_dashboard', to: 'events#unlike_dashboard'
    end
  end

  get 'dashboard', to: 'pages#dashboard'
  resources :ngos, only: [:show, :new, :create] do
    member do
      put 'follow', to: 'ngos#follow'
      put 'unfollow', to: 'ngos#unfollow'
    end
  end
end

app/views/pages/_card_event.html.erb
<div class="d-flex flex-wrap">
  <% events.each do |event| %>
    <div class="card-event-dashboard" id="card-<%= event.id  %>">
      <div class="card-event-cover">
        <%= cl_image_tag event.photo.key, alt: "event photo", class:"card-event-img",crop: :fill %>
      </div>
      <div class="card-event-infos-dashboard">
        <div class="d-flex align-self-stretch">

          <!-- Date column -->
          <div class="card-event-date col-2 text-center">
            <% if event.ngo.photo.attached? %>
              <%= cl_image_tag event.ngo.photo.key, class: "avatar-event avatar-event-card" %>
            <% end %>
            <p><%= I18n.l(event.start_date, locale: :fr, format: :day_week) %></p>
            <p id="event-day-highlight"><%= I18n.l(event.start_date, locale: :fr, format: :day) %></p>
            <p><%= I18n.l(event.start_date, locale: :fr, format: :month).upcase %></p>
            <p id="card-event-hour"><%= I18n.l(event.start_date, locale: :fr, format: :hours) %></p>
          </div>

          <!-- Infos column -->
          <div class="card-event-details col-sm-7">
            <p><%= link_to event.ngo.name, ngo_path(event.ngo), id: "card-event-ngo" %></p>
            <h2><%= event.name %></h2>
            <p><i class="fas fa-map-marker-alt"></i> <%= event.address %></p>
            <p><i class="fas fa-user-circle"></i> <%= event.seats_left %> bénévoles souhaités</p>
            <!-- Day counter -->
            <% if event.start_date > DateTime.now %>
              <p><i class="far fa-calendar-alt"></i> commence dans <%= ((event.start_date - DateTime.now) / 1.day).to_i %>
                <% if ((event.start_date - DateTime.now) / 1.day).to_i > 1 %>
                  jours
                <% else %>
                  jour
                <% end %>
              </p>
            <% elsif event.end_date > DateTime.now %>
              <p><i class="far fa-calendar-alt"></i> termine dans <%= ((event.end_date - DateTime.now) / 1.day).to_i %>
                <% if ((event.start_date - DateTime.now) / 1.day).to_i > 1 %>
                  jours
                <% else %>
                  jour
                <% end %>
              </p>
            <% else %>
              <br>
            <% end %>
          </div>

          <div class="col-sm-3">
            <!-- Bookmark -->
            <div class="bookmark-like-red mb-auto">
              <% if user_signed_in? %>
                <% if current_user.liked? event %>
                  <%= link_to unlike_dashboard_event_path(event), class:"unlike-event bookmark-like-red", method: :put, remote: true do %>
                    <i class="fas fa-bookmark" id="unlike"></i>
                  <% end %>
                <% else %>
                  <%= link_to like_event_path(event), class: "interested", remote: true, method: :put do %>
                    <i class="far fa-bookmark" id="like-event"></i>
                    <div class="infobulle" style="display: none;">
                      <div class="infobulle-texte" id="Intéressé" >
                        Intéressé(e)
                      </div>
                    </div>
                  <% end %>
                <% end  %>
              <% end %>
            </div>
            <!-- Button -->
            <%= render "shared/event_buttons", event: event %>
          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<%= render 'shared/navbar' %>

<div class="container-fluid">
  <div class="dashboard">
    <h1>Mes événements</h1>
    <p><em>Retrouvez tous les événements auxquels vous participez, ceux qui vous intéressent ainsi que les associations que vous suivez : </em></p>
    <!-- Kally : Tabs -->
    <div class="row my-3">
      <ul class="nav list-inline tabs-underlined" id="myTab" role="tablist">

        <li>
          <a href="#upcoming" class="tab-underlined active" id="upcoming-tab" data-toggle="tab" role="tab" aria-controls="upcoming" aria-selected="true">
            <i class="far fa-calendar-alt"></i>
            Actuels <span class="text-muted">(<%= @my_upcoming_events.size %>)</span>
          </a>
        </li>

        <li>
          <a href="#past" class="tab-underlined" id="past-tab" data-toggle="tab" role="tab" aria-controls="past" aria-selected="false">
            <i class="fas fa-history"></i>
            Terminés <span class="text-muted">(<%= @my_past_events.size %>)</span>
          </a>
        </li>

        <li>
          <a href="#favorite" class="tab-underlined" id="favorite-tab" data-toggle="tab" role="tab" aria-controls="favorite" aria-selected="false">
            <i class="fas fa-bookmark"></i>
            Intéressé <span class="text-muted">(<%= @events_liked.size %>)</span></a>
        </li>

        <li>
          <a href="#follow" class="tab-underlined" id="follow-tab" data-toggle="tab" role="tab" aria-controls="follow" aria-selected="false">
            <i class="fas fa-heart"></i>
            Associations <span class="text-muted">(<%= @ngos_liked.size %>)</span></a>
        </li>
      </ul>
    </div>
    <!-- End of Tabs -->

    <!-- Kally : Contents -->
    <div class="row">
      <div class="tab-content" id="myTabContent">

        <!-- Upcoming events -->
        <div class="tab-pane fade show active" id="upcoming" role="tabpanel" aria-labelledby="upcoming-tab">
          <%= render 'card_event', events: @my_upcoming_events %>
        </div>

        <!-- Past events -->
        <div class="tab-pane fade" id="past" role="tabpanel" aria-labelledby="past-tab">
          <%= render 'card_event', events: @my_past_events %>
        </div>

        <!-- Favorite events -->
        <div class="tab-pane fade" id="favorite" role="tabpanel" aria-labelledby="favorite-tab">
          <%= render 'card_event', events: @events_liked %>
        </div>

        <!-- Favorite ngos -->
        <div class="tab-pane fade" id="follow" role="tabpanel" aria-labelledby="favorite-tab">
          <!-- Ngo card -->

          <div class="d-flex flex-wrap">
            <% @ngos_liked.each do |ngo| %>
              <div class="d-flex ngo-card align-items-center ml-3">
                <% if ngo.photo.attached? %>
                  <%= cl_image_tag ngo.photo.key, class: "avatar-ngo" %>
                <% end %>
                <div class="m-3">
                  <h3><%= ngo.name %></h3>
                  <%= link_to "Voir les événéments", ngo_path(ngo)  %>
                  <div class="follow-me">
                    <% if user_signed_in?  %>
                      <% if current_user.liked? ngo %>
                        <%= link_to unfollow_ngo_path(ngo.id), class: "unfollow-ngo", remote: :true, method: :put do %>
                          <i class="fas fa-heart" id="unlike-ngo"></i>
                        <% end %>
                      <% else %>
                        <%= link_to follow_ngo_path(ngo.id), class: "follow-ngo", remote: :true, method: :put do %>
                          <i class="far fa-heart" id="like-ngo"></i>
                        <% end %>
                      <% end  %>
                    <% else %>
                        <%= link_to new_user_session_path, class: "follow-ngo" do %>
                          <i class="far fa-heart" id="like-ngo"></i>
                        <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

        </div>

      </div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<!-- yizhu: banner part -->
<%= render 'shared/navbar-home' %>
<div class="banner-hood d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1525026198548-4baa812f1183?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1533&q=80')">
<div class="container title-info">
  <div class="row justify-content-center">
    <div class="col-10">
      <!-- site title info -->
      <div class="app-title">
        <h1 class="mt-5">Commit'hood</h1>
        <h3 class="mt-3">Engagez-vous à deux pas de chez vous !</h3>
        <!-- <h3>Use your free time wisely to do something meaningful!</h3> -->
      </div>
        <div class="search-bar mt-5">
        <%= form_tag events_path, method: "get" do %>
          <div class="search-select col-5">
            <%= select_tag :user_cause, options_for_select(Cause::CAUSES), class: 'select2', :multiple => true %>
          </div>
          <%= text_field_tag :address, "", required: false, id: "event-address", label: false, placeholder: "Votre adresse" %>
          <%= submit_tag "Rechercher ", class: "btn btn-success text-white" %>
        <% end %>
        </div>
      </div>
      <!-- site title info end -->
    </div>
  </div>
</div>

<div class="container mt-2" id="inspiration" >
  <h3 class="my-4">Un peu d'inspiration 💭</h3>
</div>

    <!-- Matt : bootstrap carousel start -->
    <div id="carouselExampleIndicators" class="carousel slide carousel-card-home" data-ride="carousel">
      <ol class="carousel-indicators">
        <% i = 0 %>
        <% Event.all.each do |event| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="<%= i == 0 ? 'active' : ''%>"></li>
          <% i = i + 1 %>
        <% end %>
      </ol>
      <div class="carousel-inner">
        <% j = 0  %>
        <% Event.all.each do |event| %>
          <div class="carousel-item <%= j == 0 ? 'active' : ''%>">
            <div class="card-event-carrousel" id="event-home-<%= event.id %>">
              <div class="card-event-cover event-cover-carousel">
                <%= cl_image_tag event.photo.key, alt: "event photo", class:"card-event-img",crop: :fill %>
              </div>

              <div class="card-event-info-home">
                <div class="d-flex">

                  <!-- Date column start -->
                  <div class="card-event-date col-2 text-center">
                    <% if event.ngo.photo.attached? %>
                      <%= cl_image_tag event.ngo.photo.key, class: "avatar-event avatar-home" %>
                    <% end %>
                    <p><%= I18n.l(event.start_date, locale: :fr, format: :day_week) %></p>
                    <p class="event-day-highlight"><%= I18n.l(event.start_date, locale: :fr, format: :day) %></p>
                    <p><%= I18n.l(event.start_date, locale: :fr, format: :month).upcase %></p>
                    <p id="card-event-hour"><%= I18n.l(event.start_date, locale: :fr, format: :hours) %></p>
                  </div>
                  <!-- Date column end -->

                  <!-- Infos column start -->
                  <div class="card-event-details col-sm-8">
                    <%= link_to event.ngo.name, ngo_path(event.ngo), id: "card-event-ngo" %>
                    <h2><%= event.name %></h2>
                    <p><i class="fas fa-map-marker-alt"></i> <%= event.address %></p>
                    <p><i class="fas fa-user-circle"></i> <%= event.seats_left %> bénévoles souhaités</p>
                    <!-- Day counter -->
                    <% if event.start_date > DateTime.now %>
                      <p><i class="far fa-calendar-alt"></i> commence dans <%= ((event.start_date - DateTime.now) / 1.day).to_i %>
                        <% if ((event.start_date - DateTime.now) / 1.day).to_i > 1 %>
                          jours
                        <% else %>
                          jour
                        <% end %>
                      </p>
                    <% elsif event.end_date > DateTime.now %>
                      <p><i class="far fa-calendar-alt"></i> termine dans <%= ((event.end_date - DateTime.now) / 1.day).to_i %>
                        <% if ((event.start_date - DateTime.now) / 1.day).to_i > 1 %>
                          jours
                        <% else %>
                          jour
                        <% end %>
                      </p>
                    <% else %>
                      <br>
                    <% end %>
                    <p class="home-card-description"><%= event.description %></p>
                  </div>
                  <!-- Infos column end -->

                  <div class="d-flex text-right col-sm-3">
                    <div>
                      <%= render "shared/event_buttons", event: event %>
                    </div>
                    <!-- Bookmark -->
                    <div class="bookmark-like-red mb-auto">
                      <% if user_signed_in? %>
                        <% if current_user.liked? event %>
                          <%= link_to unlike_home_event_path(event), class:"unlike-event bookmark-like-red", method: :put, remote: true do %>
                            <i class="fas fa-bookmark" id="unlike"></i>
                          <% end %>
                        <% else %>
                          <%= link_to like_home_event_path(event), class: "interested", remote: true, method: :put do %>
                            <i class="far fa-bookmark" id="like-event"></i>
                            <div class="infobulle" style="display: none;">
                              <div class="infobulle-texte" id="Intéressé" >
                                Intéressé(e)
                              </div>
                            </div>
                          <% end %>
                        <% end  %>
                      <% end %>
                    </div>
                    <!-- Button -->
                  </div>

                </div>
              </div>
            </div>
          </div>
          <% j += 1 %>
        <% end %>

      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>